config/routes.rb
Asqus::Application.routes.draw do
  


  resources :quick_poll_types


  resources :quick_poll_responses


  resources :quick_polls


  resources :standard_poll_options


  resources :standard_poll_option_sets


  resources :tags


  resources :issues


  resources :nations


  resources :poll_options


  resources :quick_poll_options


  resources :user_groups


  resources :poll_responses


  resources :poll_questions




  resources :offices, :only => [:index, :show]


  resources :state_senate_districts


  resources :state_house_districts


  resources :counties


  resources :congressional_districts


  resources :municipalities do
    resources :wards
  end

  namespace :admin do
    resources :officials
    resources :offices
    resources :official_tenures
    resources :states
  end
  

  resources :poll_workflow_states
  resources :polls
  resources :officials, :only => [:index, :show]

 
  authenticated :user do
    root :to => 'home#home'
  end
  root :to => "home#index"
 

  match '/admin' => 'home#admin'

  devise_for :users
  resources :users

  match '/auth/:provider/callback' => 'authentications#create'
  resources :authentications, :only => [:index,:create,:destroy]
  match '/auth/failure' => 'authentications#auth_failure'



end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
  attr_accessible :group_id, :group_type, :role, :user_id

  def to_s
    return "User " + user_id.to_s +  " membership in " + group_type + " " + group_id.to_s
  end

end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  # GET /user_groups
  # GET /user_groups.json
  def index
    @user_groups = UserGroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_groups }
    end
  end

  # GET /user_groups/1
  # GET /user_groups/1.json
  def show
    @user_group = UserGroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_group }
    end
  end

  # GET /user_groups/new
  # GET /user_groups/new.json
  def new
    @user_group = UserGroup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_group }
    end
  end

  # GET /user_groups/1/edit
  def edit
    @user_group = UserGroup.find(params[:id])
  end

  # POST /user_groups
  # POST /user_groups.json
  def create
    @user_group = UserGroup.new(params[:user_group])

    respond_to do |format|
      if @user_group.save
        format.html { redirect_to @user_group, notice: 'User group was successfully created.' }
        format.json { render json: @user_group, status: :created, location: @user_group }
      else
        format.html { render action: "new" }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_groups/1
  # PUT /user_groups/1.json
  def update
    @user_group = UserGroup.find(params[:id])

    respond_to do |format|
      if @user_group.update_attributes(params[:user_group])
        format.html { redirect_to @user_group, notice: 'User group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_groups/1
  # DELETE /user_groups/1.json
  def destroy
    @user_group = UserGroup.find(params[:id])
    @user_group.destroy

    respond_to do |format|
      format.html { redirect_to user_groups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/views/user_groups/_form.html.erb
<%= simple_form_for(@user_group) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id %>
    <%= f.input :group_id %>
    <%= f.input :group_type %>
    <%= f.input :role %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/user_groups/edit.html.erb
<h1>Editing user_group</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_group %> |
<%= link_to 'Back', user_groups_path %>

app/views/user_groups/index.html.erb
<h1>Listing user_groups</h1>

<table>
  <tr>
    <th>User</th>
    <th>Group</th>
    <th>Group type</th>
    <th>Role</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_groups.each do |user_group| %>
  <tr>
    <td><%= user_group.user_id %></td>
    <td><%= user_group.group_id %></td>
    <td><%= user_group.group_type %></td>
    <td><%= user_group.role %></td>
    <td><%= link_to 'Show', user_group %></td>
    <td><%= link_to 'Edit', edit_user_group_path(user_group) %></td>
    <td><%= link_to 'Destroy', user_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User group', new_user_group_path %>

app/views/user_groups/new.html.erb
<h1>New user_group</h1>

<%= render 'form' %>

<%= link_to 'Back', user_groups_path %>

app/views/user_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @user_group.user_id %>
</p>

<p>
  <b>Group:</b>
  <%= @user_group.group_id %>
</p>

<p>
  <b>Group type:</b>
  <%= @user_group.group_type %>
</p>

<p>
  <b>Role:</b>
  <%= @user_group.role %>
</p>


<%= link_to 'Edit', edit_user_group_path(@user_group) %> |
<%= link_to 'Back', user_groups_path %>