config/routes.rb
Asqus::Application.routes.draw do
  


  resources :quick_poll_types


  resources :quick_poll_responses


  resources :quick_polls


  resources :standard_poll_options


  resources :standard_poll_option_sets


  resources :tags


  resources :issues


  resources :nations


  resources :poll_options


  resources :quick_poll_options


  resources :user_groups


  resources :poll_responses


  resources :poll_questions




  resources :offices, :only => [:index, :show]


  resources :state_senate_districts


  resources :state_house_districts


  resources :counties


  resources :congressional_districts


  resources :municipalities do
    resources :wards
  end

  namespace :admin do
    resources :officials
    resources :offices
    resources :official_tenures
    resources :states
  end
  

  resources :poll_workflow_states
  resources :polls
  resources :officials, :only => [:index, :show]

 
  authenticated :user do
    root :to => 'home#home'
  end
  root :to => "home#index"
 

  match '/admin' => 'home#admin'

  devise_for :users
  resources :users

  match '/auth/:provider/callback' => 'authentications#create'
  resources :authentications, :only => [:index,:create,:destroy]
  match '/auth/failure' => 'authentications#auth_failure'



end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @users = User.all
  end

  def home
    @users = User.all
    
    # todo: fix up this horribly inefficient code

    @state_offices = Office.where(:polity_type => 'State', :polity_id => current_user.state_id ) 
    @congressional_offices = Office.where(:polity_type => 'CongressionalDistrict', :polity_id => current_user.congressional_district_id ) 
    @municipal_offices = Office.where(:polity_type => 'Municipality', :polity_id => current_user.municipality_id ) 
    @county_offices = Office.where(:polity_type => 'County', :polity_id => current_user.county_id )

    @open_quick_polls = QuickPoll.where("id not in (select quick_poll_id from quick_poll_responses where user_id = ?)", current_user)
    @answered_quick_polls = QuickPoll.where("id in (select quick_poll_id from quick_poll_responses where user_id = ?)", current_user)
    
  end



end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/admin.html.erb
<h3>Site-Wide Administration</h3>

<p>
<p>
<%= link_to 'Users', users_path %><br>
<%= link_to 'Polities, Offices & Officials', admin_states_path %><br>
<%= link_to 'Congressional Districts', congressional_districts_path %><br>
<%= link_to 'Counties',counties_path %><br>
<%= link_to 'Municipalities',municipalities_path %><br>
<%= link_to 'State House Districts',state_house_districts_path %><br>
<%= link_to 'State Senate Districts', state_senate_districts_path %><br>
<p>
<%= link_to 'Standard Poll Options', standard_poll_option_sets_path %>

app/views/home/home.html.erb
<% user_office = offices_for_user(current_user.id).first %>
<% if !user_office.nil? %>
<b>Administration: <%= user_office.full_name %></b>
<ul>
<% new_i_path = new_issue_path + "?poller_type=Office&poller_id=" + user_office.id.to_s %>
<li><a href="<%=new_i_path %>">New Issue</a>
<% new_qp_path = new_quick_poll_path + "?poller_type=Office&poller_id=" + user_office.id.to_s %>
<li><a href="<%=new_qp_path %>">New Quick Poll</a>
</ul>

<% end %>


<h4>Your elected officials</h4>

<%# todo: fix up this horribly inefficient code %>

<table width=400>
<tr><th>Office</th><th>Incumbent</th><th></th></tr>

<% @state_offices.each do |office| %>
<% state_officer = incumbent_officials(office.id).first %>
<tr>
	<td><%= office %></td>
	<td><%= link_to state_officer.name, state_officer if !state_officer.nil? %></td>
	<td>
	  <% if !state_officer.nil? %>
	    <% if state_officer.has_photo? %>
	      <%= image_tag state_officer.photo_path %>
	    <% else %>
	      No photo.
	    <% end %>
	  <% end %>
	</td>	
</tr>
<% end %>

<% @congressional_offices.each do |office| %>
<% congressperson = incumbent_officials(office.id).first %>
<tr>
	<td><%= office %></td>
	<td><%= link_to congressperson.name, congressperson if !congressperson.nil? %></td>
	<td>
	  <% if !congressperson.nil? %>
	    <% if congressperson.has_photo? %>
	      <%= image_tag congresspeson.photo_path %>
	    <% else %>
	      No photo.
	    <% end %>
	  <% end %>
	</td>	
</tr>
<% end %>

<% @county_offices.each do |office| %>
<% county_officer = incumbent_officials(office.id).first %>
<tr>
	<td><%= office %></td>
	<td><%= link_to county_officer.name, county_officer if !county_officer.nil?%></td>
	<td>
	  <% if !county_officer.nil? %>
        <% if county_officer.has_photo? %>
	      <%= image_tag county_officer.photo_path %>
	    <% else %>
	      No photo.
	    <% end %>
	  <% end %>
	</td>
</tr>
<% end %>

<% @municipal_offices.each do |office| %>
<% municipal_officer = incumbent_officials(office.id).first %>
<tr>
	<td><%= office %></td>
	<td><%= link_to municipal_officer.name, municipal_officer if !municipal_officer.nil?%></td>
	<td>
      <% if !municipal_officer.nil? %>
	    <% if municipal_officer.has_photo? %>
		  <%= image_tag municipal_officer.photo_path %>
		<% else %>
		  No photo.
		<% end %>
      <% end %>
    </td>		
</tr>
<% end %>

</table>

<h4>Open Polls</h4>

<table width=400>
<% @open_quick_polls.each do |poll| %>
<% path = new_quick_poll_response_path + "?quick_poll_id=" + poll.id.to_s %>
<tr><td><a href=<%=path%> ><%= poll.title %></td></tr>
<% end %>
</table>

<h4>Answered Polls</h4>

<table width=400>
<% @answered_quick_polls.each do |poll| %>
<% path = quick_poll_responses_path + "?quick_poll_id=" + poll.id.to_s %>
<tr><td><a href=<%=path%> ><%= poll.title %></td></tr>
<% end %>
</table>

app/views/home/index.html.erb
Welcome to Asq.us, the town hall for the 21st century. You may log in or sign up with the links above or <a href="auth/facebook">connect with facebook</a>.