config/routes.rb
Asqus::Application.routes.draw do
  


  resources :quick_poll_types


  resources :quick_poll_responses


  resources :quick_polls


  resources :standard_poll_options


  resources :standard_poll_option_sets


  resources :tags


  resources :issues


  resources :nations


  resources :poll_options


  resources :quick_poll_options


  resources :user_groups


  resources :poll_responses


  resources :poll_questions




  resources :offices, :only => [:index, :show]


  resources :state_senate_districts


  resources :state_house_districts


  resources :counties


  resources :congressional_districts


  resources :municipalities do
    resources :wards
  end

  namespace :admin do
    resources :officials
    resources :offices
    resources :official_tenures
    resources :states
  end
  

  resources :poll_workflow_states
  resources :polls
  resources :officials, :only => [:index, :show]

 
  authenticated :user do
    root :to => 'home#home'
  end
  root :to => "home#index"
 

  match '/admin' => 'home#admin'

  devise_for :users
  resources :users

  match '/auth/:provider/callback' => 'authentications#create'
  resources :authentications, :only => [:index,:create,:destroy]
  match '/auth/failure' => 'authentications#auth_failure'



end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :taggable, :polymorphic => true
  attr_accessible :context, :tag, :taggable_id, :taggable_type
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.json
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render json: @tag, status: :created, location: @tag }
      else
        format.html { render action: "new" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.json
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= simple_form_for(@tag) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :tag %>
    <%= f.input :context %>
    <%= f.input :taggable_type %>
    <%= f.input :taggable_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>

<table>
  <tr>
    <th>Tag</th>
    <th>Context</th>
    <th>Taggable type</th>
    <th>Taggable</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tags.each do |tag| %>
  <tr>
    <td><%= tag.tag %></td>
    <td><%= tag.context %></td>
    <td><%= tag.taggable_type %></td>
    <td><%= tag.taggable_id %></td>
    <td><%= link_to 'Show', tag %></td>
    <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
    <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tag:</b>
  <%= @tag.tag %>
</p>

<p>
  <b>Context:</b>
  <%= @tag.context %>
</p>

<p>
  <b>Taggable type:</b>
  <%= @tag.taggable_type %>
</p>

<p>
  <b>Taggable:</b>
  <%= @tag.taggable_id %>
</p>


<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>