config/routes.rb
Asqus::Application.routes.draw do
  


  resources :quick_poll_types


  resources :quick_poll_responses


  resources :quick_polls


  resources :standard_poll_options


  resources :standard_poll_option_sets


  resources :tags


  resources :issues


  resources :nations


  resources :poll_options


  resources :quick_poll_options


  resources :user_groups


  resources :poll_responses


  resources :poll_questions




  resources :offices, :only => [:index, :show]


  resources :state_senate_districts


  resources :state_house_districts


  resources :counties


  resources :congressional_districts


  resources :municipalities do
    resources :wards
  end

  namespace :admin do
    resources :officials
    resources :offices
    resources :official_tenures
    resources :states
  end
  

  resources :poll_workflow_states
  resources :polls
  resources :officials, :only => [:index, :show]

 
  authenticated :user do
    root :to => 'home#home'
  end
  root :to => "home#index"
 

  match '/admin' => 'home#admin'

  devise_for :users
  resources :users

  match '/auth/:provider/callback' => 'authentications#create'
  resources :authentications, :only => [:index,:create,:destroy]
  match '/auth/failure' => 'authentications#auth_failure'



end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :congressional_districts
  has_many :state_senate_districts
  has_many :state_house_districts
  has_many :counties
  has_many :municipalities
  has_many :offices, :as => :polity, :class_name => 'Office'
  has_many :congressional_offices, :through => :congressional_districts, :class_name => 'Office', :source => :offices
  has_many :state_senate_offices, :through => :state_senate_districts, :class_name => 'Office', :source => :offices
  has_many :state_house_offices, :through => :state_house_districts, :class_name => 'Office', :source => :offices
  has_many :county_offices, :through => :counties, :class_name => 'Office', :source => :offices
  has_many :municipal_offices, :through => :municipalities, :class_name => 'Office', :source => :offices
  
  attr_accessible :abbreviation, :name

  validates_presence_of :name, :abbreviation

  def to_s
    return name
  end

end

app/controllers/admin/states_controller.rb
class Admin::StatesController < ApplicationController
  
  # GET /states
  # GET /states.json
  def index
    @states = State.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @states }
    end
  end

  # GET /states/1
  # GET /states/1.json
  def show
    @state = State.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @state }
    end
  end

  # GET /states/new
  # GET /states/new.json
  def new
    @state = State.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @state }
    end
  end

  # GET /states/1/edit
  def edit
    @state = State.find(params[:id])
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(params[:state])

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render json: @state, status: :created, location: @state }
      else
        format.html { render action: "new" }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /states/1
  # PUT /states/1.json
  def update
    @state = State.find(params[:id])

    respond_to do |format|
      if @state.update_attributes(params[:state])
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state = State.find(params[:id])
    @state.destroy

    respond_to do |format|
      format.html { redirect_to states_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  # GET /states
  # GET /states.json
  def index
    @states = State.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @states }
    end
  end

  # GET /states/1
  # GET /states/1.json
  def show
    @state = State.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @state }
    end
  end

  # GET /states/new
  # GET /states/new.json
  def new
    @state = State.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @state }
    end
  end

  # GET /states/1/edit
  def edit
    @state = State.find(params[:id])
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(params[:state])

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render json: @state, status: :created, location: @state }
      else
        format.html { render action: "new" }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /states/1
  # PUT /states/1.json
  def update
    @state = State.find(params[:id])

    respond_to do |format|
      if @state.update_attributes(params[:state])
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state = State.find(params[:id])
    @state.destroy

    respond_to do |format|
      format.html { redirect_to states_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/states_helper.rb
module Admin::StatesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/admin/states/index.html.erb
<h3>Select a State</h3>

<table width=400>
  <tr>
    <th></th>
    <th>State</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @states.each do |state| %>
  <tr>
    <td><%= state.abbreviation %></td>
    <td><%= link_to state.name, admin_state_path(state) %></td>
  </tr>
<% end %>
</table>

<br />

app/views/admin/states/show.html.erb
<p id="notice"><%= notice %></p>

<h3>State of <%= @state.name %></h3>

<ul>
<li><%= link_to "Municipalities", municipalities_path( :state_id => @state.id ) %></li>
<li><%= link_to "Counties", counties_path( :state_id => @state.id ) %></li>
</ul>

<p>
<h4>State Offices</h4>

<table width=400>
  <tr>
    <th>Office</th><th>Incumbent</th>
  </tr>

<% @state.offices.each do |office| %>
  <% incumbent = incumbent_officials(office.id).first %>
  <tr>
    <td><%= office %></td>
    <td><%= if !incumbent.nil?
              link_to incumbent.name, admin_official_path(incumbent, :state_id => @state.id )
            end            
         %>
   </td>
  </tr>
<% end %>
</table>

<h4>Congressional Districts</h4>

<table width=400>
<tr><th>District</th><th>Office</th><th>Incumbent</th>
<% @state.congressional_offices.each do |office| %>
   <% incumbent = incumbent_officials(office.id).first %>
   <tr><td><%= office.polity %></td><td><%= office %></td>
     <td>
       <%= if !incumbent.nil?
         link_to incumbent.name, admin_official_path(incumbent, :state_id => @state.id )
         end
       %> 
     </td>
   </tr>
<% end %> 
</table>

<h4>To do: something for state legislative offices</h4>


<%= link_to 'Back', admin_states_path %>